import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/ClientProvider";

export const metadata: Metadata = {
  title: "NextJS Practice Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
