import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/ClientProvider";
import UserContext from "@/context/UserContext";

export const metadata: Metadata = {
  title: "NextJS Practice Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientProvider>
          <UserContext>
            {children}
          </UserContext>
        </ClientProvider>
      </body>
    </html>
  );
}
